X-Apparently-To: proud.father@yahoo.com; Fri, 27 Sep 2019 22:38:59 +0000
Return-Path: <proud.father+caf_=proud.father=yahoo.com@gmail.com>
Authentication-Results: mta4451.mail.ne1.yahoo.com; 
 dkim=pass (ok) header.i=@kidreports.com header.s=smtpapi;
 dkim=pass (ok) header.i=@sendgrid.info header.s=smtpapi;
 spf=pass smtp.mailfrom=@gmail.com;
 dmarc=NULL(p=NULL sp=NULL dis=NULL) header.from=kidreports.com;
Received-SPF: pass (domain of gmail.com designates 209.85.208.43 as permitted sender)
X-YMailISG: uRT5vicWLDsF2A3OjKX_sYroY.AkmX.hE8tR8uFzxCD3q0QR
 xsSQ869UA_cd_offIvnXo9ceo2NFb9pB3qT.z9d60Py0q78PYISahplBU4SD
 WFat3dBq41jVE5OPb_qMzFbg6m6zBwgN7MamqJUzdST7435Fh3rUsMvKTEnc
 D72n8SqCuHq0jigTLQUK.fvxdLo69.0kcp.QbL4CUq5a.o9ppQVFd4aCBlx9
 gL3iMinH9dM.Qv34juNIbCh7d.cYDTtar.k3PI1MPqSevj71uSA_CPaC_2da
 .DZhYnBHUDejMDSD2KHwRRx1MlVenpu3k0HwxvD_FBXspJARJWgNhqm4PuqP
 m2SG.u3.5GcvpPIyJQWQ80E4l6mfmv09zoUj55m2YVyPuxBojF2LHPEudcsx
 wsTZwzoZVChTn0oewQbOZDQRgIcroEZ9YTD2ythyndb2vwnpyIjCCKplFo0M
 RDyKIE.zK64VWZqFQ_UvE94bP1FGo3shX9.HlPO3tA.KqKq7rn3BW5nGihEj
 of3Y4B5tpvzrvccp4Y5mNTiLOLJhJpM0ggvbMpvp6agFnNqQAGKqW3ZbfflR
 bWigbA9ZpnGlwLl2KkqvSsbeCbtthz1E91r1sXylHTikKbjDI2mPBPpJ8gDo
 0SkFDRq_GpT49Nn1OZXsoYRlZn79n5IpEXK6wtnHbs.mPVqaUY65wlnWXwWZ
 cZCOmQ4G4Gtw3yB_JfYDg1PYSs_l.jluSnizO9jGtapaKAn3BDiVxPoRI5Pu
 frkvN_ix9bWxMwF.0MK1P7mk38l3IlTMGnhm4CUdPNr7h4Z7ZHUMk8_QLR9X
 YxeVWf2BEl9JR5Ue7CGCPs9P5vSJPMPkOd_ydG7sIZmPyR3ESZAudy8YN..j
 spVi8a37lfM7blt7uVAtT0qi5UAUsSNbGwmum0CPBp8Hgsh165di2AebcSc8
 Q8idpKgehYz25ankCHQ913e6TNGed_ASHnsTo81ydrFxXOkeXfZcp6w_5sGE
 _naBliDdcrPoYW3wDMxhMGLxAjZPCozA3xPelvO5rEFZjv9ugFM0_u32GQWG
 89ThAqOS.UdnAmTngmotjtC3jSBAbOQ07oK9YXqvxgSddtu.tqjwA.W2Qw7z
 nX76TGnkC9LxQlcKX6X2T_r86yhbzkY.lNWMBGQdvI7Zt.kkhavNhKhfeARL
 GuufOC2nMcFNzhPqF1EUVORaWEzswPNJ.n2KxzWIi_0pLHZyXzXgq0KYtCbR
 AsV4MeSbYshewSZ4sIZZxq.T2Gbz1eA8XuDQnij6TTaKnTCkAdfubrdu_.Q.
 m4DWGz1m.UXGlD6IYAWtZXSZPa5ugnGBSre3L6h8yxH9A5iBQ15S0e3HS42S
 Up6IO9YGLYQYr4c3Z3A6COtpSSOfPONDRDwAn.Z3ooxsvdZCDK_2xUfTqRQx
 bML8GCjOLmQWSD8e2qmKtfS6colaf.3kKH7EFmW1A_uT0fbme4iTLCujHAbD
 3gNmwZ0jPLPz_TpNI4YbVmsiiEP78s9Orkh3IFe9ryUn0GwxAfEdlwiSRD53
 ovaSCpxMjxE0V42NxnASIE3gr_9X8JtUzTwB_v8CBmr0MNzt
X-Originating-IP: [209.85.208.43]
Received: from 10.217.136.215  (EHLO mail-ed1-f43.google.com) (209.85.208.43)
  by mta4451.mail.ne1.yahoo.com with SMTPS; Fri, 27 Sep 2019 22:38:58 +0000
Received: by mail-ed1-f43.google.com with SMTP id h33so3616273edh.12
        for <proud.father@yahoo.com>; Fri, 27 Sep 2019 15:38:58 -0700 (PDT)
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20161025;
        h=x-gm-message-state:delivered-to:dkim-signature:dkim-signature:date
         :from:reply-to:to:message-id:subject:mime-version;
        bh=zeI3pVeu/5KZpZd3usa0AHZD5SZdwhWafKnlbMy+H0k=;
        b=Ps90rf4SnygrXxHpGiV7AUxI6j2uOMjrNUb8bP4LgCkCzAdhTQD+KO37vJQK+4Lpqa
         Mm0sRrNAvCc28wfZB85d3v1h7+cf9Olgcbai15aA2R4UfDCp+zHl19yP7aN06Wxvbbnz
         RNe/b9TeA1fYkUQRQJfuN18Op26SY3z7ntlhB0F8qeycF4kp104jpsOwLmjE3BPqDuU9
         dg2I1pdoacZhXran7lAWLwXgFt7zxem0hbMQU5AMTLTC62gsXyyRf5+MwM1N+v5+sece
         WxEUIHOPRM+hwU5w1rm+3id5XFwiRGzoMUsPkRhw0BT6ParZNy9txdPnkpRnjGYm0PuE
         recw==
X-Gm-Message-State: APjAAAVj+1wS8NEvm3W1CT/8/eed1uTz2bEbxJNuIunP5SSxupvH8kdd
	oxuCLyCzT0UoQqvFtRIyHLWvzjYqZ3qaHpB06evZtToq+xbXQMM=
X-Received: by 2002:a05:6402:750:: with SMTP id p16mr7271122edy.188.1569623938287;
        Fri, 27 Sep 2019 15:38:58 -0700 (PDT)
X-Forwarded-To: proud.father@yahoo.com
X-Forwarded-For: proud.father@gmail.com proud.father@yahoo.com
Delivered-To: proud.father@gmail.com
Received: by 2002:a17:906:d7af:0:0:0:0 with SMTP id pk15csp4130057ejb;
        Fri, 27 Sep 2019 15:38:56 -0700 (PDT)
X-Google-Smtp-Source: APXvYqzRx/1Gm+zgfgFFdBnMZbSH4INMg0ZQTOKqIpfQBTbRruww9H4Ut9aLAJSJBVBHHnQRFPjt
X-Received: by 2002:a17:906:1a08:: with SMTP id i8mr9965239ejf.231.1569623936848;
        Fri, 27 Sep 2019 15:38:56 -0700 (PDT)
ARC-Seal: i=1; a=rsa-sha256; t=1569623936; cv=none;
        d=google.com; s=arc-20160816;
        b=b41bj5YOeD0uKF5u1y7oVlAVDAvm2QJ5cV9m07EOOBpxwcuBKi7DjAuzpH8NFd00lz
         jrRGCdocRNyT9vUMyrzHVa7yt08e1djRX0nfUlc3FgD35DfVBV6/q7A7CXxSQFlC2K16
         235eWhGfK38qyR+ihVRmzZ8FqpQ6V3kmPsAzKOTzc7l2ZyUYWdNHZN3Zj7TPExYSU8LD
         Dq8ou3rEkPJo/QC9SEoWJJD7Zzh0L17yvjjJ4AS4mIQOFs6RmPeeGDePW6FFkSio0b8/
         FuBSRgpWrMXefrxG4a1lJMIMcUmp9pEQ5PPcvuvBj/Q76YFiQ/Lf+TJtf2/eCBqd8ubd
         uFCQ==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=mime-version:subject:message-id:to:reply-to:from:date
         :dkim-signature:dkim-signature;
        bh=zeI3pVeu/5KZpZd3usa0AHZD5SZdwhWafKnlbMy+H0k=;
        b=m+HDIY7HEqRJsKZxqMZSwWZsyiBfPDhPHeZ0mkUhHc5Ts7bw9/Sd6ZBsh8gySKBG9z
         QRe6vB/gUHgK6e41oKopHUZsCedLafIfy6F7xXuSrgeNTT5hNXFzh3mXqUiUPWo7+YJV
         J5imO8PZ072VCjQinMxcs1pMqUt0penjSe1ev166ECOOwaJlK/kx+NDe4th75sNSHHaT
         JiYnpHkErO0NK+uyhBT17dEk06/X3jJ3C3PXBWch7iukzgxACnqGBpX12ncR8JYbHa8G
         YRHcfiMIL1gitGu0ti61Xoa7n61QAjfdWcE14A7jqOuJ2NULs16jmo9zM1rm7LI4J1b/
         QA/Q==
ARC-Authentication-Results: i=1; mx.google.com;
       dkim=pass header.i=@kidreports.com header.s=smtpapi header.b=kJKX9Xk0;
       dkim=pass header.i=@sendgrid.info header.s=smtpapi header.b=FiNQqQbI;
       spf=pass (google.com: domain of bounces+430342-bb0a-proud.father=gmail.com@mailer.kidreports.com designates 208.117.58.97 as permitted sender) smtp.mailfrom="bounces+430342-bb0a-proud.father=gmail.com@mailer.kidreports.com"
Return-Path: <bounces+430342-bb0a-proud.father=gmail.com@mailer.kidreports.com>
Received: from o1.mailer.kidreports.com (o1.mailer.kidreports.com. [208.117.58.97])
        by mx.google.com with ESMTPS id h53si2911905edh.147.2019.09.27.15.38.55
        for <proud.father@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Fri, 27 Sep 2019 15:38:56 -0700 (PDT)
Received-SPF: pass (google.com: domain of bounces+430342-bb0a-proud.father=gmail.com@mailer.kidreports.com designates 208.117.58.97 as permitted sender) client-ip=208.117.58.97;
Authentication-Results: mx.google.com;
       dkim=pass header.i=@kidreports.com header.s=smtpapi header.b=kJKX9Xk0;
       dkim=pass header.i=@sendgrid.info header.s=smtpapi header.b=FiNQqQbI;
       spf=pass (google.com: domain of bounces+430342-bb0a-proud.father=gmail.com@mailer.kidreports.com designates 208.117.58.97 as permitted sender) smtp.mailfrom="bounces+430342-bb0a-proud.father=gmail.com@mailer.kidreports.com"
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=kidreports.com; 
	h=from:reply-to:to:subject:mime-version:content-type; s=smtpapi; 
	bh=85ccAyM50q7VCxWm9nb3vPWMyy0=; b=kJKX9Xk08ybonkQ5qfkkvhxsohR6J
	YOoXn2f9763Bco58N+cGW38lesrKui3RSvUlnRX9Mz+BUI4TRsF0m5wb5LLnI97b
	L0xUwkV0rWW9BqN/yyscCbAM2KASmOwosRCfBOPha5YNki1r67/phZ6hm/E0ZIuo
	wQcIey0b3ELe2c=
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=sendgrid.info; 
	h=from:reply-to:to:subject:mime-version:content-type:x-feedback-id; 
	s=smtpapi; bh=85ccAyM50q7VCxWm9nb3vPWMyy0=; b=FiNQqQbIojy8rhBwWu
	qjuxT6rsNmkS88sgDEtO/FAUcxwJ6dLfHRUCfIF9tQzzAgyGy8sSQKze9hR+vcvF
	SU+OtHdfEM3t1iwbVO3YUsArOKffD9fSwS6cnQXp3yE5Zd6FZgSi+pDoF/bbYMff
	NfdGdguP/jisViAVYWspYNxZE=
Received: by filter1923p1mdw1.sendgrid.net with SMTP id filter1923p1mdw1-31104-5D8E8F7E-20
        2019-09-27 22:38:54.954823945 +0000 UTC m=+196.584660731
Received: from ip-172-30-5-125.ec2.internal (ec2-52-2-140-224.compute-1.amazonaws.com [52.2.140.224])
	by ismtpd0016p1iad2.sendgrid.net (SG) with ESMTP id nOWv0WUCS4iq3rDAPvbRXg
	for <proud.father@gmail.com>; Fri, 27 Sep 2019 22:38:54.867 +0000 (UTC)
Date: Fri, 27 Sep 2019 22:38:54 +0000 (UTC)
From: KidReports Notifier <noreply@kidreports.com>
Reply-To: "support@kidreports.com" <support@kidreports.com>
To: "proud.father@gmail.com" <proud.father@gmail.com>
Message-ID: <1574755118.1118.1569623934788.JavaMail.root@ip-172-30-5-125.ec2.internal>
Subject: Nap Event Alert
MIME-Version: 1.0
Content-Type: multipart/mixed; 
	boundary="----=_Part_1117_1300872311.1569623934787"
X-SG-EID: 7YAYQCokk9a535Xc7gPfeQh1dOizysX7VEIWqczepqCZEmilxpaZ24cFGdWDprs90+4GNK8X1SDtJT
 08l9r6z+/Hi+EvfRBud995iR5esgvYv/gwNQBQas4IR+vx9HIjfKI0k90oGgdMEk7hS8o4/+5doqWv
 rUBZcOg+1d9qwElrYHYN5SV2fe9CAxRJMsmOcumIXcKM7nPDwQC/98U2vWJUcME7iI05sDLKKjFfBj
 U=
X-SG-ID: rfGQEYwm3uCO/OWsLrh1jpaP+LkKxMZh4aisVWBV8E5G1z9O7hRiayHTQjDytIqY
X-Feedback-ID: 430342:r03ibiA3Z+9sTMY8xe7o1ogCLbJdZrcVRSF15enGbiY=:r03ibiA3Z+9sTMY8xe7o1ogCLbJdZrcVRSF15enGbiY=:SG
Content-Length: 6230

------=_Part_1117_1300872311.1569623934787
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: 7bit

<html xmlns="http://www.w3.org/1999/html">
<head>
</head>
<body style="background: white;padding: 15px;border-radius: 6px;border: 1px solid #ccc;margin: 15px;  font-family: 'Helvetica New', Helvetica, Arial, sans-serif;
font-size: 13px;
line-height: 18px;
color: #333333;
background-color: #ffffff;">
<![endif]-->
<style type="text/css">
    .disclaimer {
    font-size: 10px;
    }

    .disclaimer-footer {

    }

    body {
    margin: 0;
    font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
    font-size: 13px;
    line-height: 18px;
    color: #333333;
    background-color: #ffffff;
    }

    blockquote {
    padding: 0 0 0 15px;
    margin: 0 0 18px;
    border-left: 5px solid #eeeeee;
    }

    blockquote p {
    margin-bottom: 0;
    font-size: 16px;
    font-weight: 300;
    line-height: 22.5px;
    }

    blockquote small {
    display: block;
    line-height: 18px;
    color: #999999;
    }

    blockquote small:before {
    content: '\2014 \00A0';
    }

    blockquote.pull-right {
    float: right;
    padding-right: 15px;
    padding-left: 0;
    border-right: 5px solid #eeeeee;
    border-left: 0;
    }

    blockquote.pull-right p,
    blockquote.pull-right small {
    text-align: right;
    }

    q:before,
    q:after,
    blockquote:before,
    blockquote:after {
    content: "";
    }

    #crud #crudContent #activityContainer table tbody tr td.eventType.DailyRoutine, .DailyRoutine {
    background-color:#FFD000;
    }

    #crud #crudContent #activityContainer table tbody tr td.eventType.Administrative, .Administrative{
    background-color:#FF0000;
    color:white;
    }


    .Meals {
    background-color:#98FF00;
    }

    .dailyReportList {
    list-style: none;

    }

    .emailHeader {
    border-bottom: 1px solid #ddd;
    font-size: 30px;
    line-height: 30px;
    padding: 10px;
    }

    .emailLogo {
    margin: 10px;
    }

    .alertTime {
    border-right: 1px solid grey;
    padding-right: 5px;
    float: left;
    clear: left;
    margin-right: 5px;
    }

    .alertGroupWrapper {
    padding-left: 15px;
    }

    .alertHeader {
    padding: 5px;
    padding-left:15px;
    border-radius: 5px;
    border: 1px solid #ccc;
    margin-top: 20px;
    margin-bottom: 3px;
    }

    body.emailAlertBody {
    background: white;
    padding: 15px;
    border-radius: 6px;
    border: 1px solid #ccc;
    margin: 15px;
    }

    .emailAlertNotes {
    background-color:  #ACFCFD;
    padding: 5px;
    border-radius: 4px;
    font-weight: bold;
    }

    #crud #crudContent #activityContainer table tbody tr td.eventType.DailyRoutine, .DailyRoutine {
    background-color:#FFD000;
    }

    #crud #crudContent #activityContainer table tbody tr td.eventType.Administrative, .Administrative{
    background-color:#FF0000;
    color:white;
    }


    .Meals {
    background-color:#98FF00;
    }

</style>



<p style="border-bottom: 1px solid #ddd;font-size: 30px;line-height: 30px;padding: 10px;text-align:center;">
        <img style="margin:10px;text-align:center;" src='https://s3.amazonaws.com/kidreports-media/images/532539859/object.logo5dbjzfqex756rwz78dtcxtmckyqqx3qgxybnxp4sdx7tk5jbpx3gchnhnxfaar8e1507222469901_t.jpg'/><br/>
        <span style="text-align:center;">Sunrise Preschools #123 - n. sampl blvd #987</span>
</p>

<p><h3 style="margin-bottom: 18px;  font-size: 20px;  font-weight: 200;  line-height: 27px;">Nap Event Alert for Jenife</h3></p>
<div style="padding-left: 15px;
float: left;
clear: both;
width: 100%;">

       

<li><i class="byline alertTime" style="border-right: 1px solid grey;padding-right: 5px;float: left;clear: left;margin-right: 5px;">03:07 PM</i>
    Nap  -

                                                                                        Nap Start 3:07 PM, 
                                            Nap End 3:37 PM
                                        (sample sample)
                            



             
     
     

</li></div>

<h4 style="float: left;
width: 100%;
margin: 20px;
padding-top: 20px;"><a href="https://secure.kidreports.com">Click Here to login and modify your account details and profile.</a></h4>

<p class="poweredBy"><a href="http://www.kidreports.com">
    <img src="https://secure.kidreports.com/public/images/kidreports_t.png"/>Powered By KidReports</a>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://www.facebook.com/kidreports"><img src="https://secure.kidreports.com/public/images/f_logo16.png"/>Like</a>
    &nbsp;|&nbsp;<a href="http://www.twitter.com/kidreports"><img src="https://secure.kidreports.com/public/images/t_logo16.png"/>Follow</a>
</p>
<p style="font-size:11px; margin-top:10px;"><em>PLEASE NOTE: This email address is not monitored.  To contact KidReports Support, please send an email to <a href="mailto:support@kidreports.com">support@kidreports.com</a></em></p>
<p style="font-size:10px; margin-top:20px;">
The information contained in this email message is being transmitted to and is intended for the use of only the individual(s) to whom it is addressed.  If the reader of this message is not the intended recipient, you are hereby advised that any dissemination, distribution or copying of this message is strictly prohibited.  If you have received this message in error, please immediately delete.
<br/>
<br/>
Copyright 2011-2019 KidReports, LLC.  All Rights Reserved.
<p>

<img src="http://mailer.kidreports.com/wf/open?upn=samplesamplesampleTVbAyvJEhKqBdB2FbKOwaxbp39Zz2IgfVjoPgylGlcak9DZEFZPOF3sghOhzxMRbAwekfK-2FhvaHbNS284sw68EV5qErwEYVobfbDdzXWyX9mHNSu-2FNbCadKKruvON-2FUtyQ1gPK1JItVjy5iG6fRfbXU-2FgfJLYylPTzR8KrwU6CrI5PF2FSSrdkqLx4x8DZNygAN2GWRcr4Mjc4cH9vL4K5Vh3Mtn7v-2BWlp86jjntSSfhapAD1mw2I0KPvfjHF81nyESg-3D-3D" alt="" width="1" height="1" border="0" style="height:1px !important;width:1px !important;border-width:0 !important;margin-top:0 !important;margin-bottom:0 !important;margin-right:0 !important;margin-left:0 !important;padding-top:0 !important;padding-bottom:0 !important;padding-right:0 !important;padding-left:0 !important;"/>
</body>
</html>


------=_Part_1117_1300872311.1569623934787--

