X-Apparently-To: proud.father@yahoo.com; Wed, 25 Sep 2019 20:12:25 +0000
Return-Path: <proud.father+caf_=proud.father=yahoo.com@gmail.com>
Authentication-Results: mta4062.mail.ne1.yahoo.com; 
 dkim=pass (ok) header.i=@kidreports.com header.s=smtpapi;
 dkim=pass (ok) header.i=@sendgrid.info header.s=smtpapi;
 spf=pass smtp.mailfrom=@gmail.com;
 dmarc=NULL(p=NULL sp=NULL dis=NULL) header.from=kidreports.com;
Received-SPF: pass (domain of gmail.com designates 209.85.208.47 as permitted sender)
X-YMailISG: gKqDhY0WLDtc9ycKPLVqvA3GqVl2v82XsrMFRV1k6WaAK9bw
 e9wPe45SzRNbRutAmVDpdV8TfyGNDhRIJuRrtEfcV9Mls0K42M5cITiXN8XE
 oW1P5PNS_hoxgAYXo3rV0qpIlQUk.gdmccqc7tL0CdyYDrElN2Y8myxD3Cl6
 w.xMHvc42LVqMGNb5pwwpEqBR.qdfa7ddGyCsekMPNPvRfssLX.ArHXI3nZP
 SgZZKh1ydbiqE7cmbced.WL43b6RIC4_a3S2jD8FftWVFsApffVHQwrO0Alh
 miezKFIGOfZzbjvPClqdLgY.4v.kTIubv_DfaLBrjTa8En8K5gQE3K4mtY6O
 XYPJDb1C0ZfeHPovoikXaAE41iQMb6aGwJF2AZSzPIXo2hqd41McHZ5Q.hJ4
 UP5sJQ_mhKsBLHpXQtosM1W8ZHIbKTW_8PvVhb2n.7oXUM8kcHNVRCxmIQXs
 si8v1rYoF0ROLqlIjv8siXvNsCEFm_xxrObh0QG3mN.scjCuFAuLXmtE66G6
 udUQg37GFR0SGKETcFREtb4vkd1hS1cEYX6zGURWPjK1upX.X168uPr1U0eP
 xZnsVgvvnlptoT6m_5TlQB5DLx6EqtW1fzfn3M3mqwuKYNFuGnreqeEZ4ZWX
 L6iOdGBdg1JkOHNCwZP7.I9dVKaLThSwK5DEfhPK7BXlfyexvw1A8zIu3_SN
 PbWp_hSXnKyQp5j5bLNgjE5FaZXtvshfza5Yw_BcOIFQ9k8i8fpnb5yR9OnI
 s76lmGh0L4lxAtxw42SHlq8xY9JoOCVaCCXmZ132X.OJW7HLq94la1ffhFNW
 zEMhOOLvC_Syb49p6_IKYu3.f1RpsdaXY4P_lZlrGHHfh560r0.n9dxd2wGb
 b6WgIdhVMyuDMUlKNBcrHSvBWunloOXI9lkHiuSzpvXjlpfdqCAl53z5123D
 wHMKSAhBKuqL8Vnhg1IowIyZpz9S1h2ZD7lc3pmiiyXbxVVVEnlTe9pc99PZ
 EymZOaX_rlGbkge8cT.n2w98_guUocqL222LPA2zWzoyDP5f6_pIWmilcUNq
 qfu3oOe1qBAd6RydztFx3mpJBeZGKYT.CogyqdWiXL0Ge7WR_Y89ezhuIhrC
 otGZQDKBci_Mwdt0cVaW6XW6EcQAb1Jc_rt.UNgQw8MIe8aC5px.RuDA5axR
 jKKKi4prmLQQP_OskmJEQlwwyeBOk5XIZh5y1I1Pa5co9PTMj9z8ZSeEh88c
 pDXBLDXmfoYbR.Q4aNqUgE6hfqCIFkwf19ggOl5Mm4TAjm_J3jAx3UYF1LTD
 tH.2uWaQVOim4i8JpsEb6FQ9OaizrXzYGKGhyLGtaO3xQHS0g1hAII233rUv
 oA65xOdD3dt8FsHRtZ0K3qBMmus_Wu3VTldjErKbRswtHrgVVJSTiIT88QtY
 F4D9RYxAZbHTLNIaXpYEZmmheKCtCzjQTF10McdXwFaF8d6IfTJXJ38psWBE
 di6DH8qd2VQFTPwxk1a80q8XJ9Y1y0u1_Myslo0BtnPgULxtvJKe5nZFaZT2
 W9M8UCizCBhKRSq5LhI08PpwKfNj0KoZEe1uW_BwrAU-
X-Originating-IP: [209.85.208.47]
Received: from 10.217.137.18  (EHLO mail-ed1-f47.google.com) (209.85.208.47)
  by mta4062.mail.ne1.yahoo.com with SMTPS; Wed, 25 Sep 2019 20:12:25 +0000
Received: by mail-ed1-f47.google.com with SMTP id a15so4266440edt.6
        for <proud.father@yahoo.com>; Wed, 25 Sep 2019 13:12:25 -0700 (PDT)
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20161025;
        h=x-gm-message-state:delivered-to:dkim-signature:dkim-signature:date
         :from:reply-to:to:message-id:subject:mime-version;
        bh=3pFNb1TXMI5yh0B76P0KduOC/uxF+LUAe0pi6peuIMw=;
        b=eWfxHsjM9LWkmjHDlzidQLfc6GDsOtXnJN6YTYXgRUNgW5OV05baSQAF2dKBDv67GT
         IrDU8MxOqNDL0gt1RFYRF13QLt4879fH3YbiQKyaNaivCIzkhZhUOxWGHoIuEnaX38R8
         DA0SPu1VlhKsOgDPoCAFN/nsq9NNkt3lJdpRePRqHASf5lAXGrtTt4sVT3NYzjVFpRH3
         SH/9fl4lYdx7weHsA4yVMcekkoNL8H7rciEUNrE58aZfd6VAgtxDnvw32Z5SHxXXrd1Z
         qugORCE4N2WwyYY96232TPosEeYxlm1Lu0Irst/N+dU6/psFrEavlt5CWsjhh1Gyl5Eq
         4zwQ==
X-Gm-Message-State: APjAAAUVazjUr8+qoxiUKIp5hIKJTwrljlbjAg/7axfBJUNwzmMZcADH
	QpVTMpD4BRXSR0lPOL0rP6MNNQkjlpa5MTK4kiGh2pTbd3ylrZI=
X-Received: by 2002:aa7:d789:: with SMTP id s9mr5032487edq.62.1569442344880;
        Wed, 25 Sep 2019 13:12:24 -0700 (PDT)
X-Forwarded-To: proud.father@yahoo.com
X-Forwarded-For: proud.father@gmail.com proud.father@yahoo.com
Delivered-To: proud.father@gmail.com
Received: by 2002:a17:906:d7af:0:0:0:0 with SMTP id pk15csp1114987ejb;
        Wed, 25 Sep 2019 13:12:23 -0700 (PDT)
X-Google-Smtp-Source: APXvYqybmHoEvizvjsNrQg57VDIFwexpP0VtexLrKGQG/sy6cpSVl8gd1/cg14HOdnssD+aOpR1m
X-Received: by 2002:a17:906:7d10:: with SMTP id u16mr997765ejo.194.1569442343177;
        Wed, 25 Sep 2019 13:12:23 -0700 (PDT)
ARC-Seal: i=1; a=rsa-sha256; t=1569442343; cv=none;
        d=google.com; s=arc-20160816;
        b=UWrR5+p+sKCSf75tuINTmeecjqmTdaBbiusoLQnpDCkfwQCWPUSdXMRrprEtgOGaay
         z6De4axKb0C85APf0z9MQUERbpZcTX+V8s5GyW6fOphRgOc2PSm9HpNCFqbh9v2cgAtq
         iRJ7V/wNPlB5/FigCqY8vaMXPwOedPmqkaqIUmPeyqZZ0DoW8rsu/gXccHgBQkv9yPl2
         xteRQyY8OqpFhdMneAk+rjL9J4Mfga8Ic0mkkWrwx/8W9+FkCggH1cK3Jcu0Y5DZ/hqp
         2VlLAONerT2p15+IwizzORClWuwQOr597ZVsBwCKrOM6tUZxJKg6Bj+x9Hzw+OuVsTze
         ynxA==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=mime-version:subject:message-id:to:reply-to:from:date
         :dkim-signature:dkim-signature;
        bh=3pFNb1TXMI5yh0B76P0KduOC/uxF+LUAe0pi6peuIMw=;
        b=0UGExaNDtAMGl2Jbbe5sDhDftAnovmN3kKG/wXVgKGpoiKIO/sMfZFm1bqbd2MmaiZ
         stXs+DKpMSbDGeVSZJmxCqUpRlWDznCEKUa+Zyk4ID2xhCAvgKeTcW6N8aIu3QwImPMM
         /YcEwXCIIcLoMqMrV5CXHMCBQABIHiCz8nYNnJiWN4Tbz/lh0TdYfjJ16i3xFwC0TEVA
         lEb0MVF7gctmXgMQXAn6gpb8CwM1suo48xDf148T1KQnmJFBLlfJ/j6bbyQCeS/SkW6i
         kURiuXRZToQp8+w6anYPyHrI1P0+TQKKM3xMYkUW0qRAW1tMXFKn7Fx6tozsxBikigyW
         dJkg==
ARC-Authentication-Results: i=1; mx.google.com;
       dkim=pass header.i=@kidreports.com header.s=smtpapi header.b=EZxMfLrQ;
       dkim=pass header.i=@sendgrid.info header.s=smtpapi header.b=ZTSzT8Ic;
       spf=pass (google.com: domain of bounces+430342-bb0a-proud.father=gmail.com@mailer.kidreports.com designates 208.117.58.97 as permitted sender) smtp.mailfrom="bounces+430342-bb0a-proud.father=gmail.com@mailer.kidreports.com"
Return-Path: <bounces+430342-bb0a-proud.father=gmail.com@mailer.kidreports.com>
Received: from o1.mailer.kidreports.com (o1.mailer.kidreports.com. [208.117.58.97])
        by mx.google.com with ESMTPS id w26si42269eda.438.2019.09.25.13.12.22
        for <proud.father@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Wed, 25 Sep 2019 13:12:23 -0700 (PDT)
Received-SPF: pass (google.com: domain of bounces+430342-bb0a-proud.father=gmail.com@mailer.kidreports.com designates 208.117.58.97 as permitted sender) client-ip=208.117.58.97;
Authentication-Results: mx.google.com;
       dkim=pass header.i=@kidreports.com header.s=smtpapi header.b=EZxMfLrQ;
       dkim=pass header.i=@sendgrid.info header.s=smtpapi header.b=ZTSzT8Ic;
       spf=pass (google.com: domain of bounces+430342-bb0a-proud.father=gmail.com@mailer.kidreports.com designates 208.117.58.97 as permitted sender) smtp.mailfrom="bounces+430342-bb0a-proud.father=gmail.com@mailer.kidreports.com"
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=kidreports.com; 
	h=from:reply-to:to:subject:mime-version:content-type; s=smtpapi; 
	bh=2WgoAb2OVo5WvJEOIf5PE/cFCwo=; b=EZxMfLrQXjcRPEmQoxuADS9ppqE9K
	/PA0f7DeIpuOUgJeL79Md8gDLYKu0TNavMjjO1CmYRJTPdmoy/JMR6WRkxjjea5G
	n57wanyD8sHw/jk/Jns7Pmwqlx6tWt2ghi8BlTmh96mQ/95TsHGxuF5+de1rDEJH
	vxd6SNje/tylzA=
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=sendgrid.info; 
	h=from:reply-to:to:subject:mime-version:content-type:x-feedback-id; 
	s=smtpapi; bh=2WgoAb2OVo5WvJEOIf5PE/cFCwo=; b=ZTSzT8Ic48n17NzmzG
	cyEHWGIlNClHyxcIkjV/lceniyhALuoMl0f/LHk9iiRUldHvaLMSUM1OzfNtvvwS
	KtDzCS8WSup7d/5rxH6FkSRQSblMnmaBsHdWlkcnFXNXJCYfuVxLDf9ki1Zd80hO
	dCJnGsyQjJ0m1UNvu/ksAOZLA=
Received: by filter1383p1las1.sendgrid.net with SMTP id filter1383p1las1-29483-5D8BCA24-2F
        2019-09-25 20:12:20.469158049 +0000 UTC m=+8659.151271267
Received: from ip-172-30-5-203.ec2.internal (ec2-52-2-140-224.compute-1.amazonaws.com [52.2.140.224])
	by ismtpd0044p1mdw1.sendgrid.net (SG) with ESMTP id GVvroeICR6SVqwOzLAiOzw
	for <proud.father@gmail.com>; Wed, 25 Sep 2019 20:12:20.307 +0000 (UTC)
Date: Wed, 25 Sep 2019 20:12:20 +0000 (UTC)
From: KidReports Notifier <noreply@kidreports.com>
Reply-To: "support@kidreports.com" <support@kidreports.com>
To: "proud.father@gmail.com" <proud.father@gmail.com>
Message-ID: <410411391.662.1569442340044.JavaMail.root@ip-172-30-5-203.ec2.internal>
Subject: Bottle Event Alert
MIME-Version: 1.0
Content-Type: multipart/mixed; 
	boundary="----=_Part_661_470750339.1569442340044"
X-SG-EID: 7YAYQCokk9a535Xc7gPfeQh1dOizysX7VEIWqczepqDk8EW7G3VuLRQu39J7x3m0+XcVXqsvhjr/YJ
 fKp/i+71D3z6dfWkH9SGy09uXUHNtaw8qmcD6nlURdRbCs0WcD23JEJDozPLj98e1O09cZJTxszJ1N
 CUDoVbLNkSO2WeYyYMUzvA8MswqZu+PTAMyTK48dAr7HmA9gEzhBw5Bbeay35Cp9LeQOqhFOlXPH3W
 55+WE27EGEPAPYtHnocDBW
X-SG-ID: rfGQEYwm3uCO/OWsLrh1jo2vVfS7Q9dTISHQROJeLFFw5hqGKYW7GXO2SrlKqIUN
X-Feedback-ID: 430342:r03ibiA3Z+9sTMY8xe7o1ogCLbJdZrcVRSF15enGbiY=:r03ibiA3Z+9sTMY8xe7o1ogCLbJdZrcVRSF15enGbiY=:SG
Content-Length: 6225

------=_Part_661_470750339.1569442340044
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: 7bit

<html xmlns="http://www.w3.org/1999/html">
<head>
</head>
<body style="background: white;padding: 15px;border-radius: 6px;border: 1px solid #ccc;margin: 15px;  font-family: 'Helvetica New', Helvetica, Arial, sans-serif;
font-size: 13px;
line-height: 18px;
color: #333333;
background-color: #ffffff;">
<![endif]-->
<style type="text/css">
    .disclaimer {
    font-size: 10px;
    }

    .disclaimer-footer {

    }

    body {
    margin: 0;
    font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
    font-size: 13px;
    line-height: 18px;
    color: #333333;
    background-color: #ffffff;
    }

    blockquote {
    padding: 0 0 0 15px;
    margin: 0 0 18px;
    border-left: 5px solid #eeeeee;
    }

    blockquote p {
    margin-bottom: 0;
    font-size: 16px;
    font-weight: 300;
    line-height: 22.5px;
    }

    blockquote small {
    display: block;
    line-height: 18px;
    color: #999999;
    }

    blockquote small:before {
    content: '\2014 \00A0';
    }

    blockquote.pull-right {
    float: right;
    padding-right: 15px;
    padding-left: 0;
    border-right: 5px solid #eeeeee;
    border-left: 0;
    }

    blockquote.pull-right p,
    blockquote.pull-right small {
    text-align: right;
    }

    q:before,
    q:after,
    blockquote:before,
    blockquote:after {
    content: "";
    }

    #crud #crudContent #activityContainer table tbody tr td.eventType.DailyRoutine, .DailyRoutine {
    background-color:#FFD000;
    }

    #crud #crudContent #activityContainer table tbody tr td.eventType.Administrative, .Administrative{
    background-color:#FF0000;
    color:white;
    }


    .Meals {
    background-color:#98FF00;
    }

    .dailyReportList {
    list-style: none;

    }

    .emailHeader {
    border-bottom: 1px solid #ddd;
    font-size: 30px;
    line-height: 30px;
    padding: 10px;
    }

    .emailLogo {
    margin: 10px;
    }

    .alertTime {
    border-right: 1px solid grey;
    padding-right: 5px;
    float: left;
    clear: left;
    margin-right: 5px;
    }

    .alertGroupWrapper {
    padding-left: 15px;
    }

    .alertHeader {
    padding: 5px;
    padding-left:15px;
    border-radius: 5px;
    border: 1px solid #ccc;
    margin-top: 20px;
    margin-bottom: 3px;
    }

    body.emailAlertBody {
    background: white;
    padding: 15px;
    border-radius: 6px;
    border: 1px solid #ccc;
    margin: 15px;
    }

    .emailAlertNotes {
    background-color:  #ACFCFD;
    padding: 5px;
    border-radius: 4px;
    font-weight: bold;
    }

    #crud #crudContent #activityContainer table tbody tr td.eventType.DailyRoutine, .DailyRoutine {
    background-color:#FFD000;
    }

    #crud #crudContent #activityContainer table tbody tr td.eventType.Administrative, .Administrative{
    background-color:#FF0000;
    color:white;
    }


    .Meals {
    background-color:#98FF00;
    }

</style>



<p style="border-bottom: 1px solid #ddd;font-size: 30px;line-height: 30px;padding: 10px;text-align:center;">
        <img style="margin:10px;text-align:center;" src='https://s3.amazonaws.com/kidreports-media/images/532539859/object.logo5dbjzfqex756rwz78dtcxtmckyqqx3qgxybnxp4sdx7tk5jbpx3gchnhnxfaar8e1507222469901_t.jpg'/><br/>
        <span style="text-align:center;">Sunrise Preschools #123 - S. Sampl Road #754</span>
</p>

<p><h3 style="margin-bottom: 18px;  font-size: 20px;  font-weight: 200;  line-height: 27px;">Bottle Event Alert for Tammy1</h3></p>
<div style="padding-left: 15px;
float: left;
clear: both;
width: 100%;">

       

<li><i class="byline alertTime" style="border-right: 1px solid grey;padding-right: 5px;float: left;clear: left;margin-right: 5px;">12:30 PM</i>
    Bottle  -

                                                                                         6 1/2 oz, 
                                             Formula
                                        (Sample Sample)
                            



             
     
     

</li></div>

<h4 style="float: left;
width: 100%;
margin: 20px;
padding-top: 20px;"><a href="https://secure.kidreports.com">Click Here to login and modify your account details and profile.</a></h4>

<p class="poweredBy"><a href="http://www.kidreports.com">
    <img src="https://secure.kidreports.com/public/images/kidreports_t.png"/>Powered By KidReports</a>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://www.facebook.com/kidreports"><img src="https://secure.kidreports.com/public/images/f_logo16.png"/>Like</a>
    &nbsp;|&nbsp;<a href="http://www.twitter.com/kidreports"><img src="https://secure.kidreports.com/public/images/t_logo16.png"/>Follow</a>
</p>
<p style="font-size:11px; margin-top:10px;"><em>PLEASE NOTE: This email address is not monitored.  To contact KidReports Support, please send an email to <a href="mailto:support@kidreports.com">support@kidreports.com</a></em></p>
<p style="font-size:10px; margin-top:20px;">
The information contained in this email message is being transmitted to and is intended for the use of only the individual(s) to whom it is addressed.  If the reader of this message is not the intended recipient, you are hereby advised that any dissemination, distribution or copying of this message is strictly prohibited.  If you have received this message in error, please immediately delete.
<br/>
<br/>
Copyright 2011-2019 KidReports, LLC.  All Rights Reserved.
<p>

<img src="http://mailer.kidreports.com/wf/open?upn=SAMPLESAMPLESAMPLETVbAyvJEhKqBdB2FbKOwaxbp39Zz2IgfVjoPgylGlcak9D14f3XylWaabt-2FvcauUS7uPvn-2Bc4uCZz8Y4u6Typ-2Fr39MFgZTRAXLqiQaxofLcmg4fp26pQRw0V98i6A0r7aPrU3K9Pf0f9n9vNUjleQ9wVCCBSB1Iu9O8gxr0mo-2B28aAWa8MvBKh1soBpNX-2FUeqFu3M-2FCr0bHTr8WHrztSCNg-2FZs1mGzmtDEjwjeq1HMkOPw1iDAZW-2B9QxkVE2gCxga-2B0Q-3D-3D" alt="" width="1" height="1" border="0" style="height:1px !important;width:1px !important;border-width:0 !important;margin-top:0 !important;margin-bottom:0 !important;margin-right:0 !important;margin-left:0 !important;padding-top:0 !important;padding-bottom:0 !important;padding-right:0 !important;padding-left:0 !important;"/>
</body>
</html>


------=_Part_661_470750339.1569442340044--

